### ISSUE TITLE
An error occurred during packing

### ISSUE THREAD

**Issue by naturale0** [Nenkai/GTPSPVolTools#2]
I have successfully unpacked the GT PSP iso file. However, when I try packing, the following error occurred:

```
GTPSPVolTools by Nenkai#9075

Indexing 'C:\Users\user\Desktop\gt-vol-unpacked\' to find files to pack..
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Desktop\gt-vol-unpacked\iles.txt'.
File name: 'C:\Users\user\Desktop\gt-vol-unpacked\iles.txt'
   at System.IO.FileInfo.get_Length()
   at GTPSPVolTools.Packing.VolumeBuilder.Import(VolumeEntry parent, String folder)
   at GTPSPVolTools.Packing.VolumeBuilder.RegisterFilesToPack(String inputFolder)
   at GTPSPVolTools.Program.Pack(PackVerbs verbs)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at GTPSPVolTools.Program.Main(String[] args)
```

I guess there's something wrong with how the code handles the `files.txt` file? It would be really appreciated if you could look this through.

EDIT: I am running this in Windows 10 (21H2) x64.

**Comment by naturale0** [comment]
Solved it... Just used `C:\Users\user\Desktop\gt-vol-unpacked` instead of `C:\Users\user\Desktop\gt-vol-unpacked\` as the input. (Notice the last `\`!)

**Comment by Nenkai** [comment]
This is still a bug nonetheless, thanks for reporting. 
To be fixed shortly.
